'use client';

import type { ReactNode } from 'react';
import { BedDouble, Check, Clock3, ExternalLink, Footprints, MapPinned, Navigation, Plane, ShieldAlert, TrainFront } from 'lucide-react';
import type { Day, DayRoute, DayRouteLeg, DeadlineItem, HotelBooking, SurvivalCity, TransitDayExecution, TransportSegment } from '@/lib/types';

const statusClass = (value: string) => value === 'Confirmed' || value === 'Not Required' || value === 'Ready' ? 'confirmed' : value === 'Requested' || value === 'Required' ? 'requested' : 'unknown';
const valueOrPending = (value: number | null, suffix: string) => value == null ? '待地图复核' : `${value}${suffix}`;

export function RouteLegCard({ leg }: { leg: DayRouteLeg }) {
  const Icon = leg.recommendedMode === 'Walk' ? Footprints : TrainFront;
  return <div className="route-leg-card"><div className="route-leg-icon"><Icon /></div><div><b>{leg.from} → {leg.to}</b><span>{leg.walkMin == null ? '步行待地图复核' : `步行 ${leg.walkMin} min · ${leg.distanceKm} km`} · Taxi {leg.taxiTime}</span><small>{leg.recommended} · {leg.status === 'ROUTED' ? '真实路网' : leg.status}</small></div></div>;
}

export function TodayAtGlance({ day, route }: { day: Day; route: DayRoute }) {
  const a = route.atGlance;
  return <section className="today-glance"><header><span>TODAY AT A GLANCE</span><h2>出门前只看这一块</h2></header><div><p><b>START</b>{a.start}</p><p><b>FIRST STOP</b>{a.firstStop}</p><p><b>MUST LEAVE</b>{a.mustLeaveHotel}</p><p><b>WALKING</b>{valueOrPending(route.summary.walkingKm, ' km')} / {valueOrPending(route.summary.walkingMin, ' min')}</p><p><b>TRANSIT</b>{route.summary.transitMin == null ? '待地图复核' : `${route.summary.transitMin} min`}</p><p><b>MUST-BOOK</b>{a.mustBook}</p><p><b>MEAL</b>{a.meal}</p><p><b>GYM</b>{a.gym}</p><p><b>GOLDEN HOUR</b>{a.goldenHour}</p><p className="late"><b>LATE RULE</b>{a.lateRule}</p><p><b>BACK HOTEL</b>{a.backHotel}</p><p><b>TOMORROW</b>{a.tomorrow}</p></div><footer>Transfers {route.summary.transfers} 段 · Longest walk {valueOrPending(route.summary.longestWalkMin, ' min')} · {route.summary.status}</footer></section>;
}

function Fact({ label, children }: { label: string; children: ReactNode }) { return <p><b>{label}</b>{children}</p>; }

export function TransitExecutionCard({ execution, segment, preferred }: { execution: TransitDayExecution; segment: TransportSegment; preferred?: string }) {
  const selected = segment.candidates.find((candidate) => candidate.rank === preferred) ?? segment.candidates[0];
  return <section className="transit-execution"><header><span>TRANSIT DAY EXECUTION CARD · DAY {execution.day}</span><h2>{segment.route}</h2><p>{segment.doorToDoor}</p></header><div className="transit-execution-grid"><article><Clock3/><h3>CHECK OUT</h3><Fact label="Breakfast">{execution.checkout.breakfast}</Fact><Fact label="Check-out">{execution.checkout.checkout}</Fact><Fact label="Leave">{execution.checkout.leaveHotel}</Fact></article><article><Navigation/><h3>HOTEL → HUB</h3><Fact label="Mode">{execution.toHub.mode}</Fact><Fact label="Time">{execution.toHub.duration}</Fact><Fact label="28-inch">{execution.toHub.largeBag}</Fact><Fact label="Latest">{execution.toHub.latestLeave}</Fact></article><article><Plane/><h3>TRAIN / FLIGHT</h3><Fact label="Operator">{selected.operator ?? execution.service.operator}</Fact><Fact label="Service">{selected.service ?? execution.service.service}</Fact><Fact label="Time">{selected.departure ?? execution.service.departure} → {selected.arrival ?? execution.service.arrival}</Fact><Fact label="Buffer">{execution.service.buffer}</Fact><Fact label="Baggage">{execution.service.baggage}</Fact><span className={`execution-status ${statusClass(execution.service.status)}`}>{execution.service.status}</span></article><article><MapPinned/><h3>ARRIVAL</h3><Fact label="Route">{execution.arrival.from} → {execution.arrival.to}</Fact><Fact label="Mode">{execution.arrival.mode}</Fact><Fact label="Time">{execution.arrival.duration}</Fact><Fact label="Changes">{execution.arrival.changes}</Fact><Fact label="28-inch">{execution.arrival.largeBag}</Fact></article><article><BedDouble/><h3>LUGGAGE</h3><Fact label="Early storage">{execution.luggage.early}</Fact><Fact label="Fallback">{execution.luggage.fallback}</Fact></article><article><ShieldAlert/><h3>AFTER ARRIVAL</h3><Fact label="Can still do">{execution.afterArrival}</Fact><Fact label="+30 min">{execution.delay30}</Fact><Fact label="+60 min">{execution.delay60}</Fact><Fact label="+90 min">{execution.delay90}</Fact></article></div></section>;
}

function State({ label, value }: { label: string; value: string }) { return <p><b>{label}</b><span className={`execution-status ${statusClass(value)}`}>{value}</span></p>; }

export function HotelExecutionCard({ stay }: { stay: HotelBooking }) {
  const maps = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stay.address)}`;
  const atProperty = stay.payAtProperty ? `${stay.payAtProperty.amount} ${stay.payAtProperty.currency}` : '凭证未列';
  const cityTax = stay.payAtProperty?.label === '城市税' ? atProperty : '凭证未单列';
  const otherFees = stay.payAtProperty && stay.payAtProperty.label !== '城市税' ? `${atProperty} · ${stay.payAtProperty.label}` : '凭证未列';
  return <article className="hotel-execution-card"><header><span>{stay.city} · {stay.nights} NIGHTS</span><h2>{stay.hotelName}</h2><b>{stay.checkIn} → {stay.checkOut}</b></header><div className="hotel-photo-slots">{stay.images.map((image) => <div key={image.role}><span>{image.role}</span><b>图片待核</b></div>)}</div><div className="hotel-execution-grid"><section><h3>CHECK-IN</h3><Fact label="In / Out">{stay.checkInTime} / {stay.checkOutTime}</Fact><Fact label="Front desk">{stay.frontDeskType}</Fact><Fact label="Online">{stay.onlineCheckIn.requirement} · {stay.onlineCheckIn.status}</Fact><Fact label="Deadline">{stay.onlineCheckIn.deadline}</Fact><small>{stay.onlineCheckIn.note}</small></section><section><h3>LUGGAGE</h3><State label="Early" value={stay.luggage.early}/><State label="After checkout" value={stay.luggage.afterCheckout}/><Fact label="Location">{stay.luggage.location}</Fact><Fact label="Fee">{stay.luggage.fee}</Fact><small>{stay.luggage.note}</small></section><section><h3>ROOM</h3><Fact label="Type">{stay.roomType}</Fact><Fact label="Bed">{stay.bed}</Fact><Fact label="Bathroom">{stay.privateBathroom ? 'Confirmed private' : 'Unknown'}</Fact><Fact label="Breakfast">{stay.breakfastDetails} · {stay.breakfastTime}</Fact><Fact label="Heating">{stay.heating}</Fact></section><section><h3>PAYMENT</h3><Fact label="Paid">¥{stay.paidOnlineCny.toFixed(2)}</Fact><Fact label="At property">{atProperty}</Fact><Fact label="City tax">{cityTax}</Fact><Fact label="Other mandatory">{otherFees}</Fact><Fact label="Committed">¥{stay.committedCnyApprox.toFixed(2)}</Fact></section><section><h3>REQUEST</h3><State label="Quiet room" value={stay.requests.quietRoom}/><State label="Non-smoking" value={stay.requests.nonSmoking}/><State label="Away from elevator" value={stay.requests.awayFromElevator}/><State label="Away from street" value={stay.requests.awayFromStreet}/><State label="Away from service" value={stay.requests.awayFromServiceArea}/><small>Requested 项均 subject to availability。</small></section><section><h3>CANCELLATION</h3><Fact label="Free until">{stay.cancellation.freeUntil.replace('T',' ')}</Fact><Fact label="After deadline">{stay.cancellation.afterDeadline}</Fact><h3>CONTACT</h3><Fact label="Phone">{stay.phone}</Fact><Fact label="Address">{stay.address}</Fact><div className="hotel-card-actions"><a href={maps} target="_blank" rel="noreferrer">Google Maps <ExternalLink/></a><button onClick={() => navigator.clipboard?.writeText(stay.address)}>Copy Address</button></div></section></div></article>;
}

export function CheckinCenter({ stays, completed, setCompleted }: { stays: HotelBooking[]; completed: Record<string, boolean>; setCompleted: (value: Record<string, boolean>) => void }) {
  const ordered = [...stays].sort((a,b) => a.checkIn.localeCompare(b.checkIn));
  return <div className="checkin-center"><header><span>CHECK-IN CENTER</span><h1>在线入住集中处理</h1><p>只把真正影响进门的动作标为 Required。</p></header>{ordered.map((stay) => { const checked = completed[stay.id] ?? stay.onlineCheckIn.completionDefault; return <article key={stay.id} className={stay.onlineCheckIn.requirement === 'Required' ? 'critical' : ''}><button className={checked ? 'done' : ''} onClick={() => setCompleted({...completed,[stay.id]:!checked})}><Check/></button><div><span>{stay.checkIn} · {stay.city}</span><h2>{stay.hotelName}</h2><p>{stay.onlineCheckIn.note}</p><small>Deadline · {stay.onlineCheckIn.deadline}</small></div><b className={`execution-status ${statusClass(stay.onlineCheckIn.requirement)}`}>{stay.onlineCheckIn.requirement}</b>{stay.onlineCheckIn.link ? <a href={stay.onlineCheckIn.link} target="_blank" rel="noreferrer">Open link</a> : <span className="email-action">Open original email</span>}</article>;})}</div>;
}

export function DeadlineCenter({ items, statuses, setStatuses }: { items: DeadlineItem[]; statuses: Record<string,string>; setStatuses: (value: Record<string,string>) => void }) {
  const groups = [{key:'Critical',title:'CRITICAL TO CONFIRM'},{key:'Nice',title:'NICE TO CONFIRM'}] as const;
  return <div className="deadline-center"><header><span>DEADLINE CENTER</span><h1>关键日期集中处理</h1></header>{groups.map((group) => <section key={group.key}><h2>{group.title}</h2>{items.filter((item) => item.priority === group.key).map((item) => { const status=statuses[item.id] ?? item.status; return <article key={item.id}><time>{item.date}<small>{item.time}</small></time><div><span>{item.category}</span><h3>{item.title}</h3><p>{item.action}</p></div><select value={status} onChange={(event) => setStatuses({...statuses,[item.id]:event.target.value})}><option>Open</option><option>Ready</option><option>Waiting</option><option>Required</option><option>Done</option></select>{item.link && <a href={item.link} target="_blank" rel="noreferrer">Go to <ExternalLink/></a>}</article>;})}</section>)}</div>;
}

export function SurvivalGrid({ items, stays }: { items: SurvivalCity[]; stays: HotelBooking[] }) {
  return <div className="survival-grid">{items.map((item) => { const stay=stays.find((hotel)=>hotel.id===item.hotelId); const search=(query:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${query} near ${stay?.address ?? item.city}`)}`; return <article key={item.city}><header><span>{item.city}</span><h2>Emergency / Survival</h2></header><Fact label="Hotel">{stay?.hotelName}</Fact><Fact label="Transit">{item.nearestTransit}</Fact><a href={search('supermarket')} target="_blank" rel="noreferrer">Nearest supermarket</a><a href={search('pharmacy')} target="_blank" rel="noreferrer">Nearest pharmacy</a><a href={search('convenience food')} target="_blank" rel="noreferrer">Convenience food</a><Fact label="Station">{item.mainStation}</Fact><Fact label="Airport">{item.airport}</Fact><Fact label="Emergency">{item.emergency}</Fact><Fact label="Taxi">{item.taxi}</Fact><Fact label="Hotel phone">{item.hotelPhone}</Fact></article>;})}</div>;
}
