export const ticketBookingByEntity: Record<string, string> = {
  'activity-d1-01': 'flight-can-fco',
  'activity-d5-01': 'train-rome-florence',
  'activity-d7-01': 'train-florence-venice',
  'activity-d9-01': 'flight-vce-vie',
  'activity-d9-02': 'flight-vce-vie',
  'activity-d11-01': 'railjet-vie-prg',
  'activity-d13-01': 'flight-prg-par',
  cdg: 'flight-cdg-can',
  'activity-d17-03': 'flight-cdg-can',
  colosseum: 'colosseum',
  vatican_museums: 'vatican',
  pantheon: 'pantheon',
  st_mark_basilica: 'stmark',
  schonbrunn: 'schonbrunn',
  prague_castle: 'praguecastle',
  st_vitus: 'praguecastle',
  louvre: 'louvre',
  accademia_florence: 'accademia',
  doges_palace: 'doges-palace',
  'opt-paris-sainte': 'sainte-chapelle',
  palais_garnier: 'palais-garnier',
  arc_triomphe: 'arc',
};
